#
# (C) Copyright 2000-2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	:= mini2440.o
obj-y	+= lowlevel_init.o
#obj-$(CONFIG_NAND_S3C2440)	+= mini2440_nand.o
